import { Product } from "./types";


export const products: Product[] = [
  {
    id: "657f1e704d04e0815a4a2640",
    name: "sint nostrud excepteur esse anim",
    price: 40,
    imgUrl: "https://placehold.co/400",
    quantity: 75,
    description: "nulla cupidatat ad est minim occaecat culpa anim nostrud irure id duis sit officia magna ea aliqua veniam duis aliquip pariatur do proident aliqua consectetur",
  },
  {
    id: "657f1e702f7dea7abf5c9d0c",
    name: "ea consequat elit pariatur adipisicing",
    price: 28.99,
    imgUrl: "https://placehold.co/400",
    quantity: 82,
    description: "incididunt anim aliqua consectetur dolor cupidatat pariatur ipsum elit amet adipisicing dolore mollit et id veniam culpa eiusmod reprehenderit aute exercitation veniam commodo pariatur aliqua",
  },
  {
    id: "657f1e70930eaa595cb21799",
    name: "elit esse laboris ea ut",
    price: 13.45,
    imgUrl: "https://placehold.co/400",
    quantity: 83,
    description: "consequat adipisicing est nulla do ut aute amet labore quis irure est sint labore ipsum dolor consequat do minim irure dolore laboris do eu exercitation",
  },
  {
    id: "657f1e70edccd2bf72ab99a7",
    name: "amet laboris dolore eu ullamco",
    price: 38,
    imgUrl: "https://placehold.co/400",
    quantity: 35,
    description: "anim elit sit ex culpa enim quis nostrud tempor minim Lorem Lorem cillum adipisicing duis nulla aliqua minim labore veniam et sit et pariatur occaecat",
  },
  {
    id: "657f1e70e0658457bad2dce2",
    name: "sunt in deserunt proident esse",
    price: 33.99,
    imgUrl: "https://placehold.co/400",
    quantity: 83,
    description: "sint ea aute qui est tempor ut nisi irure mollit occaecat nisi aliquip sit proident amet aute velit eiusmod eiusmod cillum eu sint ut tempor",
  },
  {
    id: "657f1e70eac305eac9335ca6",
    name: "incididunt eu dolore mollit excepteur",
    price: 27.99,
    imgUrl: "https://placehold.co/400",
    quantity: 25,
    description: "eiusmod fugiat ullamco minim cupidatat fugiat tempor ullamco nisi reprehenderit adipisicing laborum duis consequat minim nulla est anim tempor aute pariatur nisi nostrud Lorem sint",
  },
  {
    id: "657f1e702db7e5cd11fbb88f",
    name: "ipsum culpa veniam qui sunt",
    price: 24,
    imgUrl: "https://placehold.co/400",
    quantity: 14,
    description: "proident ea ullamco elit non dolore exercitation exercitation quis sint proident id dolore elit quis incididunt labore deserunt ex eu dolore laboris exercitation aliqua commodo",
  },
  {
    id: "657f1e70039da7a6e1f71b3e",
    name: "incididunt nisi irure incididunt pariatur",
    price: 7,
    imgUrl: "https://placehold.co/400",
    quantity: 87,
    description: "laborum id do irure sunt culpa elit amet sint sit culpa aliquip laborum nostrud proident adipisicing Lorem ad dolore occaecat sunt ipsum nulla voluptate ad",
  },
  {
    id: "657f1e70f5f0a7194df4c35b",
    name: "cillum Lorem labore voluptate amet",
    price: 5.25,
    imgUrl: "https://placehold.co/400",
    quantity: 28,
    description: "tempor ullamco deserunt culpa magna veniam veniam proident sint anim ut amet qui nisi dolor ea non mollit minim cupidatat magna enim officia non cillum",
  },
  {
    id: "657f1e7046a6f4d67880950b",
    name: "velit aliquip minim sunt aute",
    price: 15,
    imgUrl: "https://placehold.co/400",
    quantity: 75,
    description: "est eu voluptate irure nostrud proident aliqua amet deserunt culpa esse labore et aute velit ex proident do commodo anim duis nisi eiusmod velit excepteur",
  },
  {
    id: "657f1e70ad679a219c3cab82",
    name: "irure sint eiusmod nulla magna",
    price: 31.99,
    imgUrl: "https://placehold.co/400",
    quantity: 77,
    description: "aliquip anim consequat voluptate veniam est cupidatat reprehenderit magna deserunt id anim veniam mollit enim esse nostrud aute magna commodo qui enim aliquip dolor et",
  },
  {
    id: "657f1e7005b94f5bdc5a1257",
    name: "ipsum id magna deserunt commodo",
    price: 36.5,
    imgUrl: "https://placehold.co/400",
    quantity: 34,
    description: "non velit aliquip consectetur anim minim sit voluptate quis sit veniam sunt sint excepteur enim Lorem ullamco est amet mollit consequat laboris et culpa exercitation",
  },
];
